name: WAAK
channels:
  - pytorch
  - conda-forge # Higher priority for general packages
  - nvidia      # For CUDA specific builds if needed
  - defaults
dependencies:
  - python=3.10
  - pip
  # Core data science and utilities
  - numpy
  - pandas
  - scipy
  - scikit-learn
  # Jupyter and interactivity
  - ipython
  - ipywidgets # Moved from pip for better conda integration
  - tqdm
  # Audio and MIDI processing - Conda preferred if available
  - mido
  - librosa
  # PyTorch ecosystem
  - pytorch
  - torchaudio
  - torchvision
  # Packages to be installed via Pip (if not on preferred conda channels or specific versions needed)
  - pip:
    - pretty_midi
    - symusic
    - midiutil
    - miditok
    - midi2audio